name: amplify_analytics_plugin_interface
description: The platform interface for the analytics module of Amplify Flutter.
version: 0.1.0
homepage: https://github.com/aws-amplify/amplify-flutter/tree/master/packages/amplify_analytics_plugin_interface

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.1.8
  # amplify_core: 0.1.0

  amplify_core:
    path: ../amplify_core
    # git:
    #   url: https://github.com/wasitu/amplify-flutter.git
    #   ref: w2
    #   path: packages/amplify_core


dev_dependencies:
  flutter_test:
    sdk: flutter
